### ISSUE TITLE
Formater plus lisiblement l'affichage du code

### ISSUE THREAD

**Issue by elias75015** [IGNF/geoportal-extensions-openlayers-samples#1]
**Cliquer sur affichage du code :** 
- une popup s'ouvre avec le code JS nécessaire à l'affichage de la carte
- scrolbar horizontale
- pas de couleur
- pas moyen de fermer la pop-up à part en scrollant tout en bas et en cliquant sur le bouton "fermer"

**Suggestions :** 
- popup plus grande
- cadre pour afficher le code, éventuellement le coloriser à la mode JS
- ajouter une croix pour fermer la popup
- éventuellement un bouton "copy to clipboard" pour ne pas avoir à selectionner manuellement le code à copier

**Comment by lowzonenose** [comment]
> ajouter une croix pour fermer la popup

Elle est en haut à droite

**Comment by lowzonenose** [comment]
> éventuellement un bouton "copy to clipboard" pour ne pas avoir à selectionner manuellement le code à copier

![image](https://user-images.githubusercontent.com/10401006/114622429-3d341c80-9cae-11eb-8ccc-337177d28b10.png)
